export { default as SearchMusic } from './SearchMusic/index.vue'
export { default as SearchArtist } from './SearchArtist/index.vue'
export { default as SearchAlbum } from './SearchAlbum/index.vue'
export { default as SearchVideo } from './SearchVideo/index.vue'
export { default as SearchPlaylist } from './SearchPlaylist/index.vue'
export { default as SearchLyric } from './SearchLyric/index.vue'
export { default as SearchRadio } from './SearchRadio/index.vue'
export { default as SearchUser } from './SearchUser/index.vue'